### ISSUE TITLE
mit aktuellen Export abgleichen

### ISSUE THREAD

**Issue by lhpitn** [zauberware/postal-codes-json-xml-csv#1]
hier ein aktueller Export aus einer Business-software, gleicht das mal miteinander ab, vielleicht ist da was neuer (oder älter dann ist die businessware nicht aktuell)

[Postleitzahlen.ods.zip](https://github.com/zauberware/postal-codes-json-xml-csv/files/3676283/Postleitzahlen.ods.zip)

Gruß

**Comment by simonfranzen** [comment]
Hey, thanks for the information. We will schedule a data update end of the year.

**Comment by simonfranzen** [comment]
hi @lhpitn ,
kannst du nochmal einen aktuellen Datensatz schicken? Woher stammt dieser? Wir haben auch gemerkt, dass einige Einträge fehlen. Ich will ein Update gerne machen. Bin unsicher, ob ich nochmal http://www.geonames.org/ nehmen soll.
