### ISSUE TITLE
Czech expression is incorrect

### ISSUE THREAD

**Issue by levistevens-dell** [zauberware/postal-codes-json-xml-csv#10]
The correct postal code value for CZ is **NNN NN**.  It is not NNNNN (NNN NN).  Checked the source geo site and confirmed this.

**Comment by simonfranzen** [comment]
<img width="1015" alt="Screenshot 2024-06-18 at 19 29 01" src="https://github.com/zauberware/postal-codes-json-xml-csv/assets/1756747/0b07c1d4-cf17-4386-b0da-0403c9e749f7">

solved with the new dataset
