### ISSUE TITLE
Fehlende Plz (zipcode)

### ISSUE THREAD

**Issue by mbecker** [zauberware/postal-codes-json-xml-csv#2]
Hi,

basierend auf den folgenden Datensätzen fehlen die unten angegebenen PLZ (zipocde):

- [https://www.suche-postleitzahl.org/downloads](https://www.suche-postleitzahl.org/downloads) (bzw. [https://www.suche-postleitzahl.org/plz-karte-erstellen](https://www.suche-postleitzahl.org/plz-karte-erstellen))
- [https://public.opendatasoft.com/explore/dataset/postleitzahlen-deutschland/export/](https://public.opendatasoft.com/explore/dataset/postleitzahlen-deutschland/export/)

```bash
06868
99095
33333
99090
06711
06485
06772
09434
15713
22961
25867
04861
82475
39217
15712
39628
64760
98694
```

**Comment by simonfranzen** [comment]
Hi @mbecker ,
die Daten sind von http://www.geonames.org/
Keine Ahnung warum dort Einträge fehlen. Wir brauchen auch dringend eine valide Liste. Hast du eine OpenData Quelle? Dann würde ich nochmal einen Abzug für JSON, XML und CSV machen.

Oder ich probiere nochmal die von http://www.geonames.org/ zu aktualisieren.

**Comment by julianbischof** [comment]
Hallo Zusammen, 

mir sind die fehlenden PLZ auch gerade aufgefallen. Aber das Thema ist hier ja bereits angesprochen worden. Aus dem Stehgreif habe ich auch keine weitern Quellen als die oben breits gelisteten. Wie ist der Status der Aktualisierung? Ein voller Datensatz ist auf jeden Fall wertvoll. :D

**Comment by corneliusroemer** [comment]
Es fehlt anscheinend auch `07740` in Jena, macht das Datenset etwas kaputt für meine Zwecke :/

**Comment by corneliusroemer** [comment]
Das statistische Bundesamt hat sicherlich eine vollständige Liste, z.B. hier:
https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugQ/AuszugGV3QAktuell.html

**Comment by simonfranzen** [comment]
I have updated the list from geonames. I have searched after your missing zipcodes.

```
06868 FOUND
15713 FOUND
39217 FOUND
15712 FOUND

```

The rest NOT :| Other Ideas to provide always latest zipcode data fro Germany?

**Comment by solverat** [comment]
Searching for _07806_ should also return "_Kospoda_" in DE (https://www.geonames.org/postalcode-search.html?q=07806&country=DE)

I think there is nothing we can do. The only alternative is to switch to google (which we **DON'T WANNA DO** :)) or using their good ol' classy board to report those missing information: http://forum.geonames.org/gforum/forums/show/7.page

**Comment by carolinscholl** [comment]
Unfortunately I was also missing the following zipcodes for Germany: 

06400 | Bernburg
12040 | Berlin
07602 | Eisenberg
73726 | Esslingen am Neckar
12414 | Berlin
65704 | Hofheim
74020 | Heilbronn
15203 | Frankfurt
31132 | Hildesheim
60590 | Frankfurt
30623 | Hannover
17475 | Greifswald
65926 | Frankfurt
23538 | Lübeck
