### ISSUE TITLE
About text a bit misleading regarding postal code amount for Germany

### ISSUE THREAD

**Issue by k00ni** [zauberware/postal-codes-json-xml-csv#5]
**About** text of this repo says:

> Collection of postal codes in different formats, ready for importing. Germany (16481 total) [...]

But after reading CSV file into a DB which has a table for each type of entity (e.g. city, postal_code, community, state, etc.) I come to the following values for Germany:
* 14.584 cities
* 7.150 postal codes
* 411 rural districts (communities?)

Some postal codes are used multiple times, like `04720` for `Döbeln` and 5 other cities (including `Großweitzschen`).

I'd say 16481 postal codes is a bit misleading and may confuse people who wanna correctness of their numbers.

What do you think?

**Comment by simonfranzen** [comment]
Hey, yes some codes are multiple times in the list. There are some villages with same postal code and I think that is ok. Postalcode are not unique.

I have updated the data from geonames and updated the numbers in the brackets.
