### ISSUE TITLE
District information 

### ISSUE THREAD

**Issue by simonfranzen** [zauberware/postal-codes-json-xml-csv#6]
After updating the database from geonames the district information are lost. 

old PR https://github.com/zauberware/postal-codes-json-xml-csv/pull/4 from @magicbrothers

**Comment by simonfranzen** [comment]
@magicbrothers maybe you have a subset of the data and I include this in the generation script?

**Comment by magicbrothers** [comment]
There's information missing in "my" data, e.g. no coordinates. But if that's no problem, I can try to extract a subset,

**Comment by simonfranzen** [comment]
I can merge those data. np

**Comment by magicbrothers** [comment]
I currently have no good idea how to efficiently extract the entries I changed.

Maybe you can just use the diff from this [commit](https://github.com/zauberware/postal-codes-json-xml-csv/commit/7f288f9053e38cd594d74b1cc26c70773d92f50a)?

**Comment by simonfranzen** [comment]
Hey, this manual adding is not future proofed. We decided to just provide the data from https://www.geonames.org/export/ 
If there is anything you need to add you have to contact them in first place. thx
