### ISSUE TITLE
Longitudinal Latitudinal Data

### ISSUE THREAD

**Issue by Erdbeergeist** [zauberware/postal-codes-json-xml-csv#7]
Hi, 

could you share how the longitudinal and latitudinal data are calculated or rather which point within the district is taken as the basis for the coordinates.

Thank you kindly

**Comment by k00ni** [comment]
I don' know it definitely, but based on README.md, data origin is http://www.geonames.org/, so you have to check them.

**Comment by Erdbeergeist** [comment]
my apologies, I should have seen that. Thank you
